# Generated by Django 4.2.6 on 2024-01-03 14:19

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yapilacaklar', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('image', models.FileField(upload_to='todo_picture')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yapilacaklar.category')),
                ('sub_category', models.ManyToManyField(to='yapilacaklar.subcategory')),
            ],
        ),
    ]
