# Generated by Django 4.2.6 on 2024-01-03 14:26

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yapilacaklar', '0003_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='todo_picture'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
